author: edupang
description: edupang's tech blog
keyword: edupang, education, developer
favicon: http://img.edupang.com/images/common/favicon.ico

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
# Projects: /project/
# About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: false

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: devpang
gitment_repo: devpang.github.io
gitment_oauth_id: d14e41087d566ca86ffb
gitment_oauth_secret: eb2a64c4bc2f5be22eeba53d336234a656672c89

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: The end is always near.
  # Links
  weibo_username: yanm1ng
  twitter_username: yanm1ng
  github_username: yanm1ng
  zhihu_username: yummy1121
  douban_username: yanm1ng